version: '3.9'

services:

  manager.support.api:
    container_name: manager-support-api
    build:
      context: src/ManagerSupport
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    # depends_on:
    #  - manager.db
    networks:
      - fucoma-app-network

  # manager.db:
  #   container_name: manager-db
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: managerdev
  #     POSTGRES_PASSWORD: managerpassdev
  #     POSTGRES_DB: ManagerDB
  #   volumes:
  #     - ./data/manager.db:/var/lib/postgresql/data
  #   networks:
  #     - fucoma-app-network

networks:
  fucoma-app-network:
    driver: bridge
