version: '3.9'

services:

  manager.support.api:
    container_name: manager-support-api
    build:
      context: src/ManagerSupport
      dockerfile: Dockerfile
      args:
         ENVIRONMENT: prod # prod or dev
    ports:
      - "8082:8082"
      - "9229:9229"
    env_file:
      - .env.dev.managersupport
    networks:
      - fucoma-app-network

networks:
  fucoma-app-network:
    name: vpsnetwork
    external: true
      

