version: '3.8'

services:

  manager.api:
    container_name: manager-api
    build:
      context: .
      dockerfile: src/Manager/Manager.API/Dockerfile
      args:
         Config_Mode: Debug
         BUILD_ENVIRONMENT: Development
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - manager.db
    networks:
      - fucoma-app-network
    ipc: host  # Grant host IPC access
    security_opt:
      - seccomp=extras/dockerconfig/seccomp_profile.json  # Mount the security profile
  
  manager.db:
    container_name: manager-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: managerdev
      POSTGRES_PASSWORD: managerpassdev
      POSTGRES_DB: ManagerDB
    volumes:
      - ./data/manager.db:/var/lib/postgresql/data
    networks:
      - fucoma-app-network

networks:
  fucoma-app-network:
    external: 
      name: vpsnetwork
