services:

  manager.api:
    container_name: manager-api
    # We can use env variable to version :latest or another value
    image: ghcr.io/davinez/manager-api:latest 
    build:
      context: .
      dockerfile: src/Manager/Manager.API/Dockerfile
      args:
         CONFIG_MODE: Debug
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env.dev.manager
    depends_on:
     - manager.db
    networks:
      - fucoma-app-network
  
  manager.db:
    container_name: manager-db
    # Docker uses the default tag latest if there are no tags defined in the pull request.
    image: postgres:16.4
    ports:
      - "5433:5433"
    environment:
      PGPORT: 5433
      POSTGRES_USER: managerdev
      POSTGRES_PASSWORD: managerpassdev
      POSTGRES_DB: ManagerDB
    volumes:
      - ./data/manager.db:/var/lib/postgresql/data
    networks:
      - fucoma-app-network

  redis:
    image: 'redis:7.4.0'
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/redis
      - ./data/redis/redis.conf:/etc/redis.conf
    environment:
      - REDIS_PASSWORD=localpass
      #- REDIS_DATABASES=16
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    networks:
     - fucoma-app-network      

networks:
  fucoma-app-network:
    name: vpsnetwork
    driver: bridge
     
