services:

  manager.support.api:
    # We can use env variable to version :latest or another value
    image: ghcr.io/davinez/manager-support-api:latest
    container_name: manager-support-api
    build:
      context: src/ManagerSupport
      dockerfile: Dockerfile # Dockerfile.debug
    ports:
      - "8082:8082"
      - "9229:9229"
    env_file:
      - .env.dev.managersupport
    networks:
      - fucoma-app-network

networks:
  fucoma-app-network:
    name: vpsnetwork
    external: true
      

