// Generated by Wrangler on Fri Jun 07 2024 23:29:32 GMT-0600 (Central Standard Time)
// by running `wrangler types`

interface Env {
	ACCESS_CODE: string;
	APPLICATION_WORKER_ID: string;
	APPLICATION_B2CEXTENSIONS_ID: string;
	TENANT_ID: string;
}
