#!/bin/sh
OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    . "$(dirname "$0")/_/husky.sh"
    cd ./src/ClientApp && npx --no-install commitlint --edit
    ;;
  'FreeBSD')
    OS='FreeBSD'
    alias ls='ls -G'
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin') 
    OS='Mac'
    ;;
  'SunOS')
    OS='Solaris'
    ;;
  'AIX') ;;
  *) ;;
esac



