#!/bin/sh
platform='unknown'
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
   ECHO $OSTYPE
elif [[ "$unamestr" == 'FreeBSDj' ]]; then
   platform='freebsd'
fi
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
. "$(dirname "$0")/_/husky.sh"
cd ./src/ClientApp && pnpm run commitlint ${1}
fi
