#!/usr/bin/env bash
# platform='unknown'
# unamestr=$(uname)
# if [[ "$unamestr" == 'Linux' ]]; then
#    platform='linux'
#    printf "dfdssfds"
#    ECHO $OSTYPE
# elif [[ "$unamestr" == 'FreeBSD' ]]; then
#    platform='freebsd'
# fi
# if [[ $platform == 'linux' ]]; then
# . "$(dirname "$0")/_/husky.sh"
# cd ./src/ClientApp && pnpm run commitizen # commitizen
# fi
echo "test"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
echo "aaaaaaaaaaa"
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
elif [[ "$OSTYPE" == "cygwin" ]]; then
        # POSIX compatibility layer and Linux environment emulation for Windows
elif [[ "$OSTYPE" == "msys" ]]; then
        # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
        echo "gfdgdfgdf"
elif [[ "$OSTYPE" == "win32" ]]; then
        # I'm not sure this can happen.
elif [[ "$OSTYPE" == "freebsd"* ]]; then
        # ...
else
        # Unknown.
fi

