#!/bin/sh
# platform='unknown'
# unamestr=$(uname)
# if [[ "$unamestr" == 'Linux' ]]; then
#    platform='linux'
#    printf "dfdssfds"
#    ECHO $OSTYPE
# elif [[ "$unamestr" == 'FreeBSD' ]]; then
#    platform='freebsd'
# fi
# if [[ $platform == 'linux' ]]; then
# . "$(dirname "$0")/_/husky.sh"
# cd ./src/ClientApp && pnpm run commitizen # commitizen
# fi
OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    alias ls='ls --color=auto'
    ;;
  'FreeBSD')
    OS='FreeBSD'
    alias ls='ls -G'
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin') 
    OS='Mac'
    ;;
  'SunOS')
    OS='Solaris'
    ;;
  'AIX') ;;
  *) ;;
esac
echo "$OS"
echo "testdsfsgfdd"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
   echo "aaaaaaaaaaa"
elif [ "$OSTYPE" == "darwin"* ]; then
     echo "gfdgdfgdf"
elif [ "$OSTYPE" == "cygwin" ]; then
     echo "gfdgdfgdf"
elif [ "$OSTYPE" == "msys" ]; then
      echo "gfdgdfgdf"
elif [ "$OSTYPE" == "win32" ]; then
      echo "gfdgdfgdf"
elif [ "$OSTYPE" == "freebsd"* ]; then
      echo "gfdgdfgdf"
else
   echo "Unknown parameter"
fi

