name: Frontend Build

on:
  push:
    paths:
      - 'src/ClientApp/**'
    branches:    
      - main

  workflow_dispatch:
 
jobs:
 # Id of the job (random string)
 build-and-push-front:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    permissions:
      contents: read
      deployments: write
    defaults:
          run:
            working-directory: 'src/ClientApp'

    steps: 
    - name: 'Checkout repository'
      uses: actions/checkout@v4 

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: pnpm install

    # Project's build step
    - name: Build
      run: pnpm run build      

    - name: Publish to Cloudfare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: 'fucoma-app'
        directory: 'src/ClientApp/dist'
        # Optional: Enable this if you want to have GitHub Deployments triggered
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
         


  

