name: Manager API Build and Test

on:
  push:
    paths:
      - 'src/Manager/**'
      - 'tests/Manager.IntegrationTests/**'
    branches:    
      - main

  # Allow manually trigger of the jobs
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  GITHUB_USERNAME: ${{ github.repository_owner }}
  IMAGE_NAME: manager-api
  BUILD_CONFIGURATION: Release
  CONTAINER_APP_NAME: manager-api
  RESOURCE_GROUP: fucoma-prod-rg

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
 # Id of the job (random string)
 test-manager:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    defaults:
        run:
          working-directory: './'

    steps:  

    # Login With OpenID Connect (OIDC) 
    # more https://github.com/marketplace/actions/azure-login#login-with-openid-connect-oidc-recommended
    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Retrieve secret from Key Vault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          KeyVault-Test-Endpoint=$(az keyvault secret show --name "KeyVault-Test-Endpoint" --vault-name "fucoma-config-vault" --query "value" -o tsv)
          echo "::add-mask::$KeyVault-Test-Endpoint"
          echo "KEY_VAULT_TEST_ENDPOINT="$KeyVault-Test-Endpoint >> $GITHUB_ENV

          Azure-Client-Id=$(az keyvault secret show --name "Azure-Client-Id" --vault-name "fucoma-config-vault" --query "value" -o tsv)
          echo "::add-mask::$Azure-Client-Id"
          echo "AZURE_CLIENT_ID="$Azure-Client-Id >> $GITHUB_ENV

          Azure-Client-Secret=$(az keyvault secret show --name "Azure-Client-Secret" --vault-name "fucoma-config-vault" --query "value" -o tsv)
          echo "::add-mask::$Azure-Client-Secret"
          echo "AZURE_CLIENT_SECRET="$Azure-Client-Secret >> $GITHUB_ENV

          Azure-Tenant-Id=$(az keyvault secret show --name "Azure-Tenant-Id" --vault-name "fucoma-config-vault" --query "value" -o tsv)
          echo "::add-mask::$Azure-Tenant-Id"
          echo "AZURE_CLIENT_SECRET="$Azure-Tenant-Id >> $GITHUB_ENV

    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # You can test your matrix by printing the current dotnet version
    - name: Display dotnet version
      run: dotnet --version  
     
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test with the dotnet CLI
      run: dotnet test --no-restore --results-directory "TestResults-${{ matrix.dotnet-version }}" --configuration Release

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

 build-and-push-manager-image:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.sha_short.outputs.SHORT_SHA }}
    needs: [test-manager]
    defaults:
          run:
            working-directory: './'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}       

      - name: Add SHORT_SHA env property with commit short sha
        id: sha_short
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_OUTPUT

      # If using variable ${{ github.repository }} => The owner and repository name. For example, octocat/Hello-World
      - name: 'Build, tag, and push image to GitHub Container Registry (Packages)'
        # | called a Literal Block Scalar which preserves new lines and trailing spaces
        # > called a Folded Block Scalar which converts new lines into spaces
        # \ break same command in lines
        run: |
          docker build . \
            --build-arg BUILD_CONFIGURATION=${{ env.BUILD_CONFIGURATION }} \
            --tag ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha_short.outputs.SHORT_SHA }} \
            -f src/Manager/Manager.API/Dockerfile 
          docker push ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha_short.outputs.SHORT_SHA }}

# Id of the job (random string)
 azure-deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-manager-image]
    defaults:
        run:
          working-directory: './'

    steps:  

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Build and deploy the container app
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ghcr.io/davinez/manager-support-api:${{ needs.build-and-push-manager-image.outputs.short-sha }}
        registryUrl: ${{ env.REGISTRY }}
        registryUsername: ${{ secrets.REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.REGISTRY_TOKEN }} 
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }} 


