name: Trigger auto deployment for manager-support-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/manager-support-api-AutoDeployTrigger-e8b56d2c-47da-41b2-b83c-4f4b8c40e7ed.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MANAGERSUPPORTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MANAGERSUPPORTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MANAGERSUPPORTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MANAGERSUPPORTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MANAGERSUPPORTAPI_REGISTRY_PASSWORD }}
          containerAppName: manager-support-api
          resourceGroup: fucoma-prod-rg
          imageToBuild: ghcr.io/manager-support-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


